# fly.toml app configuration file generated for initiative-tracker on 2025-09-13T15:32:55+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'initiative-tracker'
primary_region = 'syd'

[build]
  dockerfile = './Dockerfile'

[env]
  DB_PATH = '/data/catalog.db'
  NODE_ENV = 'production'
  PORT = '3000'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
