app = "initiative-tracker"
primary_region = "syd"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  DB_PATH = "/data/catalog.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "data"
  destination = "/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
